### PR TITLE
Add `help_wanted` template

### PR DESCRIPTION
**Pull request by grouville**
Help wanted template

@mircubed, here is the implementation of the template + a preview of what it looks like locally: 
image
[help-wanted-template.pdf](https://github.com/dagger/.github/files/8755049/help-wanted-template.pdf).

Signed-off-by: guillaume

### CODE REVIEW

**Comment by mircubed** [comment]
@marcosnils can you update this with the latest changes that we made today (like the intro)?

**Comment by mircubed** [comment]
@marcosnils to review on Thursday, so we can add the new intro

**Comment by mircubed** [comment]
https://docs.google.com/document/d/1Xngmd0Icc5H47eOO2doT_HTV65bKj_zNBXLnmmnzd3U/edit @gerhard @marcosnils please review google docs template to match this one.

**Comment by marcosnils** [comment]
@mircubed please LMK when this is ready for another pass :pray:

**Comment by mircubed** [comment]
@marcosnils can you add the following and we can update the intro on Thursday? Then, we can push this on Thursday early morning. 


Add - 

Text box:
Title: Execution URL
Value: URL of the dagger execution (if applicable)

**Comment by marcosnils** [comment]
Done @mircubed, you should see the new field now. LMK if you need me to change anything :pray:

**Comment by gerhard** [comment]
Thank you @grouville! 🚀

**Pull request merged**
